# Generated by Django 2.1.3 on 2018-11-27 00:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(on_delete='cascade', to='dashboard.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=280)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('column', models.ForeignKey(on_delete='cascade', to='dashboard.Column')),
                ('in_charge', models.ForeignKey(default=django.contrib.auth.models.User, on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
